/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client.resources.trace;

import ai.proofstate.client.core.ClientOptions;
import ai.proofstate.client.core.RequestOptions;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import ai.proofstate.client.resources.trace.requests.DeleteTracesRequest;
import ai.proofstate.client.resources.trace.types.DeleteTraceResponse;

public class AsyncTraceClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawTraceClient rawClient;

  public AsyncTraceClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawTraceClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawTraceClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Delete a specific trace
   */
  public CompletableFuture<DeleteTraceResponse> delete(String traceId) {
    return this.rawClient.delete(traceId).thenApply(response -> response.body());
  }

  /**
   * Delete a specific trace
   */
  public CompletableFuture<DeleteTraceResponse> delete(String traceId,
      RequestOptions requestOptions) {
    return this.rawClient.delete(traceId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Delete multiple traces
   */
  public CompletableFuture<DeleteTraceResponse> deleteMultiple(DeleteTracesRequest request) {
    return this.rawClient.deleteMultiple(request).thenApply(response -> response.body());
  }

  /**
   * Delete multiple traces
   */
  public CompletableFuture<DeleteTraceResponse> deleteMultiple(DeleteTracesRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.deleteMultiple(request, requestOptions).thenApply(response -> response.body());
  }
}
