/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client.resources.opentelemetry;

import ai.proofstate.client.core.ClientOptions;
import ai.proofstate.client.core.RequestOptions;
import ai.proofstate.client.resources.opentelemetry.requests.OtelTraceRequest;
import ai.proofstate.client.resources.opentelemetry.types.OtelTraceResponse;

public class OpentelemetryClient {
  protected final ClientOptions clientOptions;

  private final RawOpentelemetryClient rawClient;

  public OpentelemetryClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawOpentelemetryClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawOpentelemetryClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * <strong>OpenTelemetry Traces Ingestion Endpoint</strong>
   * <p>This endpoint implements the OTLP/HTTP specification for trace ingestion, providing native OpenTelemetry integration for ProofState Observability.</p>
   * <p><strong>Supported Formats:</strong></p>
   * <ul>
   * <li>Binary Protobuf: <code>Content-Type: application/x-protobuf</code></li>
   * <li>JSON Protobuf: <code>Content-Type: application/json</code></li>
   * <li>Supports gzip compression via <code>Content-Encoding: gzip</code> header</li>
   * </ul>
   * <p><strong>Specification Compliance:</strong></p>
   * <ul>
   * <li>Conforms to <a href="https://opentelemetry.io/docs/specs/otlp/#otlphttp">OTLP/HTTP Trace Export</a></li>
   * <li>Implements <code>ExportTraceServiceRequest</code> message format</li>
   * </ul>
   */
  public OtelTraceResponse exportTraces(OtelTraceRequest request) {
    return this.rawClient.exportTraces(request).body();
  }

  /**
   * <strong>OpenTelemetry Traces Ingestion Endpoint</strong>
   * <p>This endpoint implements the OTLP/HTTP specification for trace ingestion, providing native OpenTelemetry integration for ProofState Observability.</p>
   * <p><strong>Supported Formats:</strong></p>
   * <ul>
   * <li>Binary Protobuf: <code>Content-Type: application/x-protobuf</code></li>
   * <li>JSON Protobuf: <code>Content-Type: application/json</code></li>
   * <li>Supports gzip compression via <code>Content-Encoding: gzip</code> header</li>
   * </ul>
   * <p><strong>Specification Compliance:</strong></p>
   * <ul>
   * <li>Conforms to <a href="https://opentelemetry.io/docs/specs/otlp/#otlphttp">OTLP/HTTP Trace Export</a></li>
   * <li>Implements <code>ExportTraceServiceRequest</code> message format</li>
   * </ul>
   */
  public OtelTraceResponse exportTraces(OtelTraceRequest request, RequestOptions requestOptions) {
    return this.rawClient.exportTraces(request, requestOptions).body();
  }
}
