/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client.resources.health.errors;

import ai.proofstate.client.core.ProofStateClientApiException;
import java.lang.Object;
import okhttp3.Response;

public final class ServiceUnavailableError extends ProofStateClientApiException {
  public ServiceUnavailableError(Object body) {
    super("ServiceUnavailableError", 503, body);
  }

  public ServiceUnavailableError(Object body, Response rawResponse) {
    super("ServiceUnavailableError", 503, body, rawResponse);
  }
}
