/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client.resources.score;

import ai.proofstate.client.core.ClientOptions;
import ai.proofstate.client.core.RequestOptions;
import java.lang.String;
import ai.proofstate.client.resources.score.types.CreateScoreRequest;
import ai.proofstate.client.resources.score.types.CreateScoreResponse;

public class ScoreClient {
  protected final ClientOptions clientOptions;

  private final RawScoreClient rawClient;

  public ScoreClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawScoreClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawScoreClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Create a score (supports both trace and session scores)
   */
  public CreateScoreResponse create(CreateScoreRequest request) {
    return this.rawClient.create(request).body();
  }

  /**
   * Create a score (supports both trace and session scores)
   */
  public CreateScoreResponse create(CreateScoreRequest request, RequestOptions requestOptions) {
    return this.rawClient.create(request, requestOptions).body();
  }

  /**
   * Delete a score (supports both trace and session scores)
   */
  public void delete(String scoreId) {
    this.rawClient.delete(scoreId).body();
  }

  /**
   * Delete a score (supports both trace and session scores)
   */
  public void delete(String scoreId, RequestOptions requestOptions) {
    this.rawClient.delete(scoreId, requestOptions).body();
  }
}
