/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client.analytics.resources.commons.types;

import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.Optional;

public interface IDatasetRun {
  String getId();

  String getName();

  Optional<String> getDescription();

  Object getMetadata();

  String getDatasetId();

  String getDatasetName();

  OffsetDateTime getCreatedAt();

  OffsetDateTime getUpdatedAt();
}
