/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client.analytics.resources.commons.types;

import java.lang.String;
import java.time.OffsetDateTime;

public interface ISession {
  String getId();

  OffsetDateTime getCreatedAt();

  String getProjectId();

  String getEnvironment();
}
