/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client.analytics.resources.commons.types;

import ai.proofstate.client.analytics.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import java.io.IOException;
import java.lang.IllegalStateException;
import java.lang.Object;
import java.lang.RuntimeException;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;

@JsonDeserialize(
    using = PricingTierCondition.Deserializer.class
)
public final class PricingTierCondition {
  private final Object value;

  private final int type;

  private PricingTierCondition(Object value, int type) {
    this.value = value;
    this.type = type;
  }

  @JsonValue
  public Object get() {
    return this.value;
  }

  @SuppressWarnings("unchecked")
  public <T> T visit(Visitor<T> visitor) {
    if(this.type == 0) {
      return visitor.visit((PricingTierUsageCondition) this.value);
    } else if(this.type == 1) {
      return visitor.visit((PricingTierAttributeCondition) this.value);
    }
    throw new IllegalStateException("Failed to visit value. This should never happen.");
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PricingTierCondition && equalTo((PricingTierCondition) other);
  }

  private boolean equalTo(PricingTierCondition other) {
    return value.equals(other.value);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.value);
  }

  @java.lang.Override
  public String toString() {
    return this.value.toString();
  }

  public static PricingTierCondition of(PricingTierUsageCondition value) {
    return new PricingTierCondition(value, 0);
  }

  public static PricingTierCondition of(PricingTierAttributeCondition value) {
    return new PricingTierCondition(value, 1);
  }

  public interface Visitor<T> {
    T visit(PricingTierUsageCondition value);

    T visit(PricingTierAttributeCondition value);
  }

  static final class Deserializer extends StdDeserializer<PricingTierCondition> {
    Deserializer() {
      super(PricingTierCondition.class);
    }

    @java.lang.Override
    public PricingTierCondition deserialize(JsonParser p, DeserializationContext context) throws
        IOException {
      Object value = p.readValueAs(Object.class);
      try {
        return of(ObjectMappers.JSON_MAPPER.convertValue(value, PricingTierUsageCondition.class));
      } catch(RuntimeException e) {
      }
      try {
        return of(ObjectMappers.JSON_MAPPER.convertValue(value, PricingTierAttributeCondition.class));
      } catch(RuntimeException e) {
      }
      throw new JsonParseException(p, "Failed to deserialize");
    }
  }
}
