/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client.analytics.resources.commons.types;

import ai.proofstate.client.analytics.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PricingTierInput.Builder.class
)
public final class PricingTierInput {
  private final String name;

  private final Optional<Boolean> isDefault;

  private final int priority;

  private final List<PricingTierConditionInput> conditions;

  private final Map<String, Double> prices;

  private final Map<String, Object> additionalProperties;

  private PricingTierInput(String name, Optional<Boolean> isDefault, int priority,
      List<PricingTierConditionInput> conditions, Map<String, Double> prices,
      Map<String, Object> additionalProperties) {
    this.name = name;
    this.isDefault = isDefault;
    this.priority = priority;
    this.conditions = conditions;
    this.prices = prices;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Name of the pricing tier for display and identification purposes.
   * <p>Must be unique within the model. Common patterns: &quot;Standard&quot;, &quot;High Volume Tier&quot;, &quot;Extended Context&quot;</p>
   */
  @JsonProperty("name")
  public String getName() {
    return name;
  }

  /**
   * @return Whether this is the default tier. Exactly one tier per model must be marked as default.
   * <p>Requirements for default tier:</p>
   * <ul>
   * <li>Must have isDefault=true</li>
   * <li>Must have priority=0</li>
   * <li>Must have empty conditions array (conditions=[])</li>
   * </ul>
   * <p>The default tier acts as a fallback when no conditional tiers match. Defaults to false when omitted.</p>
   */
  @JsonProperty("isDefault")
  public Optional<Boolean> getIsDefault() {
    return isDefault;
  }

  /**
   * @return Priority for tier matching evaluation. Lower numbers = higher priority (evaluated first).
   * <p>Must be unique within the model. The default tier must have priority=0.
   * Conditional tiers should use priority 1, 2, 3, etc. based on their specificity.</p>
   */
  @JsonProperty("priority")
  public int getPriority() {
    return priority;
  }

  /**
   * @return Array of conditions that must ALL be met for this tier to match (AND logic).
   * <p>The default tier must have an empty array (conditions=[]).
   * Conditional tiers should define one or more conditions that specify when this tier's pricing applies.</p>
   * <p>Conditions can compare summed matching usage details to a numeric threshold, or exactly match a top-level model parameter or metadata value.</p>
   */
  @JsonProperty("conditions")
  public List<PricingTierConditionInput> getConditions() {
    return conditions;
  }

  /**
   * @return Prices (USD) by usage type for this tier. At least one price must be defined.
   * <p>Common usage types: &quot;input&quot;, &quot;output&quot;, &quot;total&quot;, &quot;request&quot;, &quot;image&quot;
   * Prices are in USD per unit (e.g., per token).</p>
   * <p>Example: {&quot;input&quot;: 0.000003, &quot;output&quot;: 0.000015} represents $3 per million input tokens and $15 per million output tokens.</p>
   */
  @JsonProperty("prices")
  public Map<String, Double> getPrices() {
    return prices;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PricingTierInput && equalTo((PricingTierInput) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PricingTierInput other) {
    return name.equals(other.name) && isDefault.equals(other.isDefault) && priority == other.priority && conditions.equals(other.conditions) && prices.equals(other.prices);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.name, this.isDefault, this.priority, this.conditions, this.prices);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static NameStage builder() {
    return new Builder();
  }

  public interface NameStage {
    /**
     * <p>Name of the pricing tier for display and identification purposes.</p>
     * <p>Must be unique within the model. Common patterns: &quot;Standard&quot;, &quot;High Volume Tier&quot;, &quot;Extended Context&quot;</p>
     */
    PriorityStage name(@NotNull String name);

    Builder from(PricingTierInput other);
  }

  public interface PriorityStage {
    /**
     * <p>Priority for tier matching evaluation. Lower numbers = higher priority (evaluated first).</p>
     * <p>Must be unique within the model. The default tier must have priority=0.
     * Conditional tiers should use priority 1, 2, 3, etc. based on their specificity.</p>
     */
    _FinalStage priority(int priority);
  }

  public interface _FinalStage {
    PricingTierInput build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Whether this is the default tier. Exactly one tier per model must be marked as default.</p>
     * <p>Requirements for default tier:</p>
     * <ul>
     * <li>Must have isDefault=true</li>
     * <li>Must have priority=0</li>
     * <li>Must have empty conditions array (conditions=[])</li>
     * </ul>
     * <p>The default tier acts as a fallback when no conditional tiers match. Defaults to false when omitted.</p>
     */
    _FinalStage isDefault(Optional<Boolean> isDefault);

    _FinalStage isDefault(Boolean isDefault);

    /**
     * <p>Array of conditions that must ALL be met for this tier to match (AND logic).</p>
     * <p>The default tier must have an empty array (conditions=[]).
     * Conditional tiers should define one or more conditions that specify when this tier's pricing applies.</p>
     * <p>Conditions can compare summed matching usage details to a numeric threshold, or exactly match a top-level model parameter or metadata value.</p>
     */
    _FinalStage conditions(List<PricingTierConditionInput> conditions);

    _FinalStage addConditions(PricingTierConditionInput conditions);

    _FinalStage addAllConditions(List<PricingTierConditionInput> conditions);

    /**
     * <p>Prices (USD) by usage type for this tier. At least one price must be defined.</p>
     * <p>Common usage types: &quot;input&quot;, &quot;output&quot;, &quot;total&quot;, &quot;request&quot;, &quot;image&quot;
     * Prices are in USD per unit (e.g., per token).</p>
     * <p>Example: {&quot;input&quot;: 0.000003, &quot;output&quot;: 0.000015} represents $3 per million input tokens and $15 per million output tokens.</p>
     */
    _FinalStage prices(Map<String, Double> prices);

    _FinalStage putAllPrices(Map<String, Double> prices);

    _FinalStage prices(String key, Double value);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements NameStage, PriorityStage, _FinalStage {
    private String name;

    private int priority;

    private Map<String, Double> prices = new LinkedHashMap<>();

    private List<PricingTierConditionInput> conditions = new ArrayList<>();

    private Optional<Boolean> isDefault = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PricingTierInput other) {
      name(other.getName());
      isDefault(other.getIsDefault());
      priority(other.getPriority());
      conditions(other.getConditions());
      prices(other.getPrices());
      return this;
    }

    /**
     * <p>Name of the pricing tier for display and identification purposes.</p>
     * <p>Must be unique within the model. Common patterns: &quot;Standard&quot;, &quot;High Volume Tier&quot;, &quot;Extended Context&quot;</p>
     * <p>Name of the pricing tier for display and identification purposes.</p>
     * <p>Must be unique within the model. Common patterns: &quot;Standard&quot;, &quot;High Volume Tier&quot;, &quot;Extended Context&quot;</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("name")
    public PriorityStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    /**
     * <p>Priority for tier matching evaluation. Lower numbers = higher priority (evaluated first).</p>
     * <p>Must be unique within the model. The default tier must have priority=0.
     * Conditional tiers should use priority 1, 2, 3, etc. based on their specificity.</p>
     * <p>Priority for tier matching evaluation. Lower numbers = higher priority (evaluated first).</p>
     * <p>Must be unique within the model. The default tier must have priority=0.
     * Conditional tiers should use priority 1, 2, 3, etc. based on their specificity.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("priority")
    public _FinalStage priority(int priority) {
      this.priority = priority;
      return this;
    }

    /**
     * <p>Prices (USD) by usage type for this tier. At least one price must be defined.</p>
     * <p>Common usage types: &quot;input&quot;, &quot;output&quot;, &quot;total&quot;, &quot;request&quot;, &quot;image&quot;
     * Prices are in USD per unit (e.g., per token).</p>
     * <p>Example: {&quot;input&quot;: 0.000003, &quot;output&quot;: 0.000015} represents $3 per million input tokens and $15 per million output tokens.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage prices(String key, Double value) {
      this.prices.put(key, value);
      return this;
    }

    /**
     * <p>Prices (USD) by usage type for this tier. At least one price must be defined.</p>
     * <p>Common usage types: &quot;input&quot;, &quot;output&quot;, &quot;total&quot;, &quot;request&quot;, &quot;image&quot;
     * Prices are in USD per unit (e.g., per token).</p>
     * <p>Example: {&quot;input&quot;: 0.000003, &quot;output&quot;: 0.000015} represents $3 per million input tokens and $15 per million output tokens.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage putAllPrices(Map<String, Double> prices) {
      if (prices != null) {
        this.prices.putAll(prices);
      }
      return this;
    }

    /**
     * <p>Prices (USD) by usage type for this tier. At least one price must be defined.</p>
     * <p>Common usage types: &quot;input&quot;, &quot;output&quot;, &quot;total&quot;, &quot;request&quot;, &quot;image&quot;
     * Prices are in USD per unit (e.g., per token).</p>
     * <p>Example: {&quot;input&quot;: 0.000003, &quot;output&quot;: 0.000015} represents $3 per million input tokens and $15 per million output tokens.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "prices",
        nulls = Nulls.SKIP
    )
    public _FinalStage prices(Map<String, Double> prices) {
      this.prices.clear();
      if (prices != null) {
        this.prices.putAll(prices);
      }
      return this;
    }

    /**
     * <p>Array of conditions that must ALL be met for this tier to match (AND logic).</p>
     * <p>The default tier must have an empty array (conditions=[]).
     * Conditional tiers should define one or more conditions that specify when this tier's pricing applies.</p>
     * <p>Conditions can compare summed matching usage details to a numeric threshold, or exactly match a top-level model parameter or metadata value.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAllConditions(List<PricingTierConditionInput> conditions) {
      if (conditions != null) {
        this.conditions.addAll(conditions);
      }
      return this;
    }

    /**
     * <p>Array of conditions that must ALL be met for this tier to match (AND logic).</p>
     * <p>The default tier must have an empty array (conditions=[]).
     * Conditional tiers should define one or more conditions that specify when this tier's pricing applies.</p>
     * <p>Conditions can compare summed matching usage details to a numeric threshold, or exactly match a top-level model parameter or metadata value.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addConditions(PricingTierConditionInput conditions) {
      this.conditions.add(conditions);
      return this;
    }

    /**
     * <p>Array of conditions that must ALL be met for this tier to match (AND logic).</p>
     * <p>The default tier must have an empty array (conditions=[]).
     * Conditional tiers should define one or more conditions that specify when this tier's pricing applies.</p>
     * <p>Conditions can compare summed matching usage details to a numeric threshold, or exactly match a top-level model parameter or metadata value.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "conditions",
        nulls = Nulls.SKIP
    )
    public _FinalStage conditions(List<PricingTierConditionInput> conditions) {
      this.conditions.clear();
      if (conditions != null) {
        this.conditions.addAll(conditions);
      }
      return this;
    }

    /**
     * <p>Whether this is the default tier. Exactly one tier per model must be marked as default.</p>
     * <p>Requirements for default tier:</p>
     * <ul>
     * <li>Must have isDefault=true</li>
     * <li>Must have priority=0</li>
     * <li>Must have empty conditions array (conditions=[])</li>
     * </ul>
     * <p>The default tier acts as a fallback when no conditional tiers match. Defaults to false when omitted.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage isDefault(Boolean isDefault) {
      this.isDefault = Optional.ofNullable(isDefault);
      return this;
    }

    /**
     * <p>Whether this is the default tier. Exactly one tier per model must be marked as default.</p>
     * <p>Requirements for default tier:</p>
     * <ul>
     * <li>Must have isDefault=true</li>
     * <li>Must have priority=0</li>
     * <li>Must have empty conditions array (conditions=[])</li>
     * </ul>
     * <p>The default tier acts as a fallback when no conditional tiers match. Defaults to false when omitted.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "isDefault",
        nulls = Nulls.SKIP
    )
    public _FinalStage isDefault(Optional<Boolean> isDefault) {
      this.isDefault = isDefault;
      return this;
    }

    @java.lang.Override
    public PricingTierInput build() {
      return new PricingTierInput(name, isDefault, priority, conditions, prices, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
