/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client.analytics.resources.commons.types;

import ai.proofstate.client.analytics.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PricingTierAttributeCondition.Builder.class
)
public final class PricingTierAttributeCondition {
  private final PricingTierAttributeSource source;

  private final String key;

  private final List<String> values;

  private final Map<String, Object> additionalProperties;

  private PricingTierAttributeCondition(PricingTierAttributeSource source, String key,
      List<String> values, Map<String, Object> additionalProperties) {
    this.source = source;
    this.key = key;
    this.values = values;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Observation attribute object evaluated by this condition.
   */
  @JsonProperty("source")
  public PricingTierAttributeSource getSource() {
    return source;
  }

  /**
   * @return Exact top-level attribute key.
   */
  @JsonProperty("key")
  public String getKey() {
    return key;
  }

  /**
   * @return Membership operator.
   */
  @JsonProperty("operator")
  public String getOperator() {
    return "in";
  }

  /**
   * @return Accepted string attribute values. At least one value is required.
   */
  @JsonProperty("values")
  public List<String> getValues() {
    return values;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PricingTierAttributeCondition && equalTo((PricingTierAttributeCondition) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PricingTierAttributeCondition other) {
    return source.equals(other.source) && key.equals(other.key) && values.equals(other.values);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.source, this.key, this.values);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static SourceStage builder() {
    return new Builder();
  }

  public interface SourceStage {
    /**
     * <p>Observation attribute object evaluated by this condition.</p>
     */
    KeyStage source(@NotNull PricingTierAttributeSource source);

    Builder from(PricingTierAttributeCondition other);
  }

  public interface KeyStage {
    /**
     * <p>Exact top-level attribute key.</p>
     */
    _FinalStage key(@NotNull String key);
  }

  public interface _FinalStage {
    PricingTierAttributeCondition build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Accepted string attribute values. At least one value is required.</p>
     */
    _FinalStage values(List<String> values);

    _FinalStage addValues(String values);

    _FinalStage addAllValues(List<String> values);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements SourceStage, KeyStage, _FinalStage {
    private PricingTierAttributeSource source;

    private String key;

    private List<String> values = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PricingTierAttributeCondition other) {
      source(other.getSource());
      key(other.getKey());
      values(other.getValues());
      return this;
    }

    /**
     * <p>Observation attribute object evaluated by this condition.</p>
     * <p>Observation attribute object evaluated by this condition.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("source")
    public KeyStage source(@NotNull PricingTierAttributeSource source) {
      this.source = Objects.requireNonNull(source, "source must not be null");
      return this;
    }

    /**
     * <p>Exact top-level attribute key.</p>
     * <p>Exact top-level attribute key.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("key")
    public _FinalStage key(@NotNull String key) {
      this.key = Objects.requireNonNull(key, "key must not be null");
      return this;
    }

    /**
     * <p>Accepted string attribute values. At least one value is required.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAllValues(List<String> values) {
      if (values != null) {
        this.values.addAll(values);
      }
      return this;
    }

    /**
     * <p>Accepted string attribute values. At least one value is required.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addValues(String values) {
      this.values.add(values);
      return this;
    }

    /**
     * <p>Accepted string attribute values. At least one value is required.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "values",
        nulls = Nulls.SKIP
    )
    public _FinalStage values(List<String> values) {
      this.values.clear();
      if (values != null) {
        this.values.addAll(values);
      }
      return this;
    }

    @java.lang.Override
    public PricingTierAttributeCondition build() {
      return new PricingTierAttributeCondition(source, key, values, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
