/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client.analytics.resources.commons.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class PricingTierAttributeSource {
  public static final PricingTierAttributeSource MODEL_PARAMETERS = new PricingTierAttributeSource(Value.MODEL_PARAMETERS, "model_parameters");

  public static final PricingTierAttributeSource METADATA = new PricingTierAttributeSource(Value.METADATA, "metadata");

  private final Value value;

  private final String string;

  PricingTierAttributeSource(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other)
      || (other instanceof PricingTierAttributeSource && this.string.equals(((PricingTierAttributeSource) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case MODEL_PARAMETERS:
        return visitor.visitModelParameters();
      case METADATA:
        return visitor.visitMetadata();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static PricingTierAttributeSource valueOf(String value) {
    switch (value) {
      case "model_parameters":
        return MODEL_PARAMETERS;
      case "metadata":
        return METADATA;
      default:
        return new PricingTierAttributeSource(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    MODEL_PARAMETERS,

    METADATA,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitModelParameters();

    T visitMetadata();

    T visitUnknown(String unknownType);
  }
}
