/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client.analytics.resources.commons.types;

import ai.proofstate.client.analytics.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PricingTierUsageConditionInput.Builder.class
)
public final class PricingTierUsageConditionInput {
  private final String usageDetailPattern;

  private final PricingTierOperator operator;

  private final double value;

  private final Optional<Boolean> caseSensitive;

  private final Map<String, Object> additionalProperties;

  private PricingTierUsageConditionInput(String usageDetailPattern, PricingTierOperator operator,
      double value, Optional<Boolean> caseSensitive, Map<String, Object> additionalProperties) {
    this.usageDetailPattern = usageDetailPattern;
    this.operator = operator;
    this.value = value;
    this.caseSensitive = caseSensitive;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Regex pattern matched against usage detail keys.
   */
  @JsonProperty("usageDetailPattern")
  public String getUsageDetailPattern() {
    return usageDetailPattern;
  }

  @JsonProperty("operator")
  public PricingTierOperator getOperator() {
    return operator;
  }

  /**
   * @return Numeric threshold for the summed matching usage values.
   */
  @JsonProperty("value")
  public double getValue() {
    return value;
  }

  /**
   * @return Whether the usage-detail regex is case-sensitive. Defaults to false.
   */
  @JsonProperty("caseSensitive")
  public Optional<Boolean> getCaseSensitive() {
    return caseSensitive;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PricingTierUsageConditionInput && equalTo((PricingTierUsageConditionInput) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PricingTierUsageConditionInput other) {
    return usageDetailPattern.equals(other.usageDetailPattern) && operator.equals(other.operator) && value == other.value && caseSensitive.equals(other.caseSensitive);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.usageDetailPattern, this.operator, this.value, this.caseSensitive);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static UsageDetailPatternStage builder() {
    return new Builder();
  }

  public interface UsageDetailPatternStage {
    /**
     * <p>Regex pattern matched against usage detail keys.</p>
     */
    OperatorStage usageDetailPattern(@NotNull String usageDetailPattern);

    Builder from(PricingTierUsageConditionInput other);
  }

  public interface OperatorStage {
    ValueStage operator(@NotNull PricingTierOperator operator);
  }

  public interface ValueStage {
    /**
     * <p>Numeric threshold for the summed matching usage values.</p>
     */
    _FinalStage value(double value);
  }

  public interface _FinalStage {
    PricingTierUsageConditionInput build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Whether the usage-detail regex is case-sensitive. Defaults to false.</p>
     */
    _FinalStage caseSensitive(Optional<Boolean> caseSensitive);

    _FinalStage caseSensitive(Boolean caseSensitive);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements UsageDetailPatternStage, OperatorStage, ValueStage, _FinalStage {
    private String usageDetailPattern;

    private PricingTierOperator operator;

    private double value;

    private Optional<Boolean> caseSensitive = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PricingTierUsageConditionInput other) {
      usageDetailPattern(other.getUsageDetailPattern());
      operator(other.getOperator());
      value(other.getValue());
      caseSensitive(other.getCaseSensitive());
      return this;
    }

    /**
     * <p>Regex pattern matched against usage detail keys.</p>
     * <p>Regex pattern matched against usage detail keys.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("usageDetailPattern")
    public OperatorStage usageDetailPattern(@NotNull String usageDetailPattern) {
      this.usageDetailPattern = Objects.requireNonNull(usageDetailPattern, "usageDetailPattern must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("operator")
    public ValueStage operator(@NotNull PricingTierOperator operator) {
      this.operator = Objects.requireNonNull(operator, "operator must not be null");
      return this;
    }

    /**
     * <p>Numeric threshold for the summed matching usage values.</p>
     * <p>Numeric threshold for the summed matching usage values.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("value")
    public _FinalStage value(double value) {
      this.value = value;
      return this;
    }

    /**
     * <p>Whether the usage-detail regex is case-sensitive. Defaults to false.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage caseSensitive(Boolean caseSensitive) {
      this.caseSensitive = Optional.ofNullable(caseSensitive);
      return this;
    }

    /**
     * <p>Whether the usage-detail regex is case-sensitive. Defaults to false.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "caseSensitive",
        nulls = Nulls.SKIP
    )
    public _FinalStage caseSensitive(Optional<Boolean> caseSensitive) {
      this.caseSensitive = caseSensitive;
      return this;
    }

    @java.lang.Override
    public PricingTierUsageConditionInput build() {
      return new PricingTierUsageConditionInput(usageDetailPattern, operator, value, caseSensitive, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
