/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client.analytics.resources.commons.errors;

import ai.proofstate.client.analytics.core.ProofStateAnalyticsClientApiException;
import java.lang.Object;
import okhttp3.Response;

public final class Error extends ProofStateAnalyticsClientApiException {
  /**
   * The body of the response that triggered the exception.
   */
  private final Object body;

  public Error(Object body) {
    super("Error", 400, body);
    this.body = body;
  }

  public Error(Object body, Response rawResponse) {
    super("Error", 400, body, rawResponse);
    this.body = body;
  }

  /**
   * @return the body
   */
  @java.lang.Override
  public Object body() {
    return this.body;
  }
}
