/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client.resources.commons.errors;

import ai.proofstate.client.core.ProofStateClientApiException;
import java.lang.Object;
import okhttp3.Response;

public final class MethodNotAllowedError extends ProofStateClientApiException {
  /**
   * The body of the response that triggered the exception.
   */
  private final Object body;

  public MethodNotAllowedError(Object body) {
    super("MethodNotAllowedError", 405, body);
    this.body = body;
  }

  public MethodNotAllowedError(Object body, Response rawResponse) {
    super("MethodNotAllowedError", 405, body, rawResponse);
    this.body = body;
  }

  /**
   * @return the body
   */
  @java.lang.Override
  public Object body() {
    return this.body;
  }
}
