/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client.resources.models;

import ai.proofstate.client.core.ClientOptions;
import ai.proofstate.client.core.RequestOptions;
import java.lang.String;
import ai.proofstate.client.resources.commons.types.Model;
import ai.proofstate.client.resources.models.requests.GetModelsRequest;
import ai.proofstate.client.resources.models.types.CreateModelRequest;
import ai.proofstate.client.resources.models.types.PaginatedModels;

public class ModelsClient {
  protected final ClientOptions clientOptions;

  private final RawModelsClient rawClient;

  public ModelsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawModelsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawModelsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Create a model
   */
  public Model create(CreateModelRequest request) {
    return this.rawClient.create(request).body();
  }

  /**
   * Create a model
   */
  public Model create(CreateModelRequest request, RequestOptions requestOptions) {
    return this.rawClient.create(request, requestOptions).body();
  }

  /**
   * Get all models
   */
  public PaginatedModels list() {
    return this.rawClient.list().body();
  }

  /**
   * Get all models
   */
  public PaginatedModels list(RequestOptions requestOptions) {
    return this.rawClient.list(requestOptions).body();
  }

  /**
   * Get all models
   */
  public PaginatedModels list(GetModelsRequest request) {
    return this.rawClient.list(request).body();
  }

  /**
   * Get all models
   */
  public PaginatedModels list(GetModelsRequest request, RequestOptions requestOptions) {
    return this.rawClient.list(request, requestOptions).body();
  }

  /**
   * Get a model
   */
  public Model get(String id) {
    return this.rawClient.get(id).body();
  }

  /**
   * Get a model
   */
  public Model get(String id, RequestOptions requestOptions) {
    return this.rawClient.get(id, requestOptions).body();
  }

  /**
   * Delete a model. Cannot delete models managed by ProofState. You can create your own definition with the same modelName to override the definition though.
   */
  public void delete(String id) {
    this.rawClient.delete(id).body();
  }

  /**
   * Delete a model. Cannot delete models managed by ProofState. You can create your own definition with the same modelName to override the definition though.
   */
  public void delete(String id, RequestOptions requestOptions) {
    this.rawClient.delete(id, requestOptions).body();
  }
}
