/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client.resources.metricsv2;

import com.fasterxml.jackson.core.JsonProcessingException;
import ai.proofstate.client.core.ClientOptions;
import ai.proofstate.client.core.ProofStateClientApiException;
import ai.proofstate.client.core.ProofStateClientException;
import ai.proofstate.client.core.ProofStateClientHttpResponse;
import ai.proofstate.client.core.ObjectMappers;
import ai.proofstate.client.core.QueryStringMapper;
import ai.proofstate.client.core.RequestOptions;
import java.io.IOException;
import java.lang.Object;
import java.lang.String;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;
import ai.proofstate.client.resources.commons.errors.AccessDeniedError;
import ai.proofstate.client.resources.commons.errors.Error;
import ai.proofstate.client.resources.commons.errors.MethodNotAllowedError;
import ai.proofstate.client.resources.commons.errors.NotFoundError;
import ai.proofstate.client.resources.commons.errors.UnauthorizedError;
import ai.proofstate.client.resources.metricsv2.requests.GetMetricsV2Request;
import ai.proofstate.client.resources.metricsv2.types.MetricsV2Response;

public class RawMetricsV2Client {
  protected final ClientOptions clientOptions;

  public RawMetricsV2Client(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Get metrics from the ProofState project using a query object. V2 endpoint with optimized performance.
   */
  public ProofStateClientHttpResponse<MetricsV2Response> metrics(GetMetricsV2Request request) {
    return metrics(request,null);
  }

  /**
   * Get metrics from the ProofState project using a query object. V2 endpoint with optimized performance.
   */
  public ProofStateClientHttpResponse<MetricsV2Response> metrics(GetMetricsV2Request request,
      RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
      .addPathSegments("api/public")
      .addPathSegments("v2/metrics");QueryStringMapper.addQueryParameter(httpUrl, "query", request.getQuery(), false);
      if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        if (response.isSuccessful()) {
          return new ProofStateClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, MetricsV2Response.class), response);
        }
        try {
          switch (response.code()) {
            case 400:throw new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            case 403:throw new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            case 405:throw new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
          }
        }
        catch (JsonProcessingException ignored) {
          // unable to map error response, throwing generic error
        }
        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
        throw new ProofStateClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
      }
      catch (IOException e) {
        throw new ProofStateClientException("Network error executing HTTP request", e);
      }
    }
  }
