/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client.resources.health;

import com.fasterxml.jackson.core.JsonProcessingException;
import ai.proofstate.client.core.ClientOptions;
import ai.proofstate.client.core.ProofStateClientApiException;
import ai.proofstate.client.core.ProofStateClientException;
import ai.proofstate.client.core.ProofStateClientHttpResponse;
import ai.proofstate.client.core.ObjectMappers;
import ai.proofstate.client.core.RequestOptions;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;
import ai.proofstate.client.resources.commons.errors.AccessDeniedError;
import ai.proofstate.client.resources.commons.errors.Error;
import ai.proofstate.client.resources.commons.errors.MethodNotAllowedError;
import ai.proofstate.client.resources.commons.errors.NotFoundError;
import ai.proofstate.client.resources.commons.errors.UnauthorizedError;
import ai.proofstate.client.resources.health.errors.ServiceUnavailableError;
import ai.proofstate.client.resources.health.types.HealthResponse;

public class AsyncRawHealthClient {
  protected final ClientOptions clientOptions;

  public AsyncRawHealthClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Check health of API and database
   */
  public CompletableFuture<ProofStateClientHttpResponse<HealthResponse>> health() {
    return health(null);
  }

  /**
   * Check health of API and database
   */
  public CompletableFuture<ProofStateClientHttpResponse<HealthResponse>> health(
      RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
      .addPathSegments("api/public")
      .addPathSegments("health");if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request okhttpRequest = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json")
        .build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<ProofStateClientHttpResponse<HealthResponse>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              future.complete(new ProofStateClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HealthResponse.class), response));
              return;
            }
            try {
              switch (response.code()) {
                case 400:future.completeExceptionally(new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
                case 401:future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
                case 403:future.completeExceptionally(new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
                case 404:future.completeExceptionally(new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
                case 405:future.completeExceptionally(new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
                case 503:future.completeExceptionally(new ServiceUnavailableError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            future.completeExceptionally(new ProofStateClientApiException("Error with status code " + response.code(), response.code(), errorBody, response));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new ProofStateClientException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new ProofStateClientException("Network error executing HTTP request", e));
        }
      });
      return future;
    }
  }
