/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client.resources.health;

import ai.proofstate.client.core.ClientOptions;
import ai.proofstate.client.core.RequestOptions;
import ai.proofstate.client.resources.health.types.HealthResponse;

public class HealthClient {
  protected final ClientOptions clientOptions;

  private final RawHealthClient rawClient;

  public HealthClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawHealthClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawHealthClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Check health of API and database
   */
  public HealthResponse health() {
    return this.rawClient.health().body();
  }

  /**
   * Check health of API and database
   */
  public HealthResponse health(RequestOptions requestOptions) {
    return this.rawClient.health(requestOptions).body();
  }
}
