/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client.analytics;

import ai.proofstate.client.analytics.core.ClientOptions;
import ai.proofstate.client.analytics.core.Suppliers;
import ai.proofstate.client.analytics.resources.experiments.AsyncExperimentsClient;
import ai.proofstate.client.analytics.resources.scoresv3.AsyncScoresV3Client;
import java.util.function.Supplier;

public class AsyncProofStateAnalyticsClient {
  protected final ClientOptions clientOptions;

  protected final Supplier<AsyncExperimentsClient> experimentsClient;

  protected final Supplier<AsyncScoresV3Client> scoresV3Client;

  public AsyncProofStateAnalyticsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.experimentsClient = Suppliers.memoize(() -> new AsyncExperimentsClient(clientOptions));
    this.scoresV3Client = Suppliers.memoize(() -> new AsyncScoresV3Client(clientOptions));
  }

  public AsyncExperimentsClient experiments() {
    return this.experimentsClient.get();
  }

  public AsyncScoresV3Client scoresV3() {
    return this.scoresV3Client.get();
  }

  public static AsyncProofStateAnalyticsClientBuilder builder() {
    return new AsyncProofStateAnalyticsClientBuilder();
  }
}
