/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client.analytics;

import ai.proofstate.client.analytics.core.ClientOptions;
import ai.proofstate.client.analytics.core.Suppliers;
import ai.proofstate.client.analytics.resources.experiments.ExperimentsClient;
import ai.proofstate.client.analytics.resources.scoresv3.ScoresV3Client;
import java.util.function.Supplier;

public class ProofStateAnalyticsClient {
  protected final ClientOptions clientOptions;

  protected final Supplier<ExperimentsClient> experimentsClient;

  protected final Supplier<ScoresV3Client> scoresV3Client;

  public ProofStateAnalyticsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.experimentsClient = Suppliers.memoize(() -> new ExperimentsClient(clientOptions));
    this.scoresV3Client = Suppliers.memoize(() -> new ScoresV3Client(clientOptions));
  }

  public ExperimentsClient experiments() {
    return this.experimentsClient.get();
  }

  public ScoresV3Client scoresV3() {
    return this.scoresV3Client.get();
  }

  public static ProofStateAnalyticsClientBuilder builder() {
    return new ProofStateAnalyticsClientBuilder();
  }
}
