/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client.core;

import java.lang.Exception;
import java.lang.RuntimeException;
import java.lang.String;

/**
 * This class serves as the base exception for all errors in the SDK.
 */
public class ProofStateClientException extends RuntimeException {
  public ProofStateClientException(String message) {
    super(message);
  }

  public ProofStateClientException(String message, Exception e) {
    super(message, e);
  }
}
