/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client.resources.media;

import ai.proofstate.client.core.ClientOptions;
import ai.proofstate.client.core.RequestOptions;
import java.lang.String;
import java.lang.Void;
import java.util.concurrent.CompletableFuture;
import ai.proofstate.client.resources.media.types.GetMediaResponse;
import ai.proofstate.client.resources.media.types.GetMediaUploadUrlRequest;
import ai.proofstate.client.resources.media.types.GetMediaUploadUrlResponse;
import ai.proofstate.client.resources.media.types.PatchMediaBody;

public class AsyncMediaClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawMediaClient rawClient;

  public AsyncMediaClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawMediaClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawMediaClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Get a media record
   */
  public CompletableFuture<GetMediaResponse> get(String mediaId) {
    return this.rawClient.get(mediaId).thenApply(response -> response.body());
  }

  /**
   * Get a media record
   */
  public CompletableFuture<GetMediaResponse> get(String mediaId, RequestOptions requestOptions) {
    return this.rawClient.get(mediaId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Patch a media record
   */
  public CompletableFuture<Void> patch(String mediaId, PatchMediaBody request) {
    return this.rawClient.patch(mediaId, request).thenApply(response -> response.body());
  }

  /**
   * Patch a media record
   */
  public CompletableFuture<Void> patch(String mediaId, PatchMediaBody request,
      RequestOptions requestOptions) {
    return this.rawClient.patch(mediaId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get a presigned upload URL for a media record
   */
  public CompletableFuture<GetMediaUploadUrlResponse> getUploadUrl(
      GetMediaUploadUrlRequest request) {
    return this.rawClient.getUploadUrl(request).thenApply(response -> response.body());
  }

  /**
   * Get a presigned upload URL for a media record
   */
  public CompletableFuture<GetMediaUploadUrlResponse> getUploadUrl(GetMediaUploadUrlRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getUploadUrl(request, requestOptions).thenApply(response -> response.body());
  }
}
