/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client.resources.scoreconfigs;

import ai.proofstate.client.core.ClientOptions;
import ai.proofstate.client.core.RequestOptions;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import ai.proofstate.client.resources.commons.types.ScoreConfig;
import ai.proofstate.client.resources.scoreconfigs.requests.GetScoreConfigsRequest;
import ai.proofstate.client.resources.scoreconfigs.types.CreateScoreConfigRequest;
import ai.proofstate.client.resources.scoreconfigs.types.ScoreConfigs;
import ai.proofstate.client.resources.scoreconfigs.types.UpdateScoreConfigRequest;

public class AsyncScoreConfigsClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawScoreConfigsClient rawClient;

  public AsyncScoreConfigsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawScoreConfigsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawScoreConfigsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Create a score configuration (config). Score configs are used to define the structure of scores
   */
  public CompletableFuture<ScoreConfig> create(CreateScoreConfigRequest request) {
    return this.rawClient.create(request).thenApply(response -> response.body());
  }

  /**
   * Create a score configuration (config). Score configs are used to define the structure of scores
   */
  public CompletableFuture<ScoreConfig> create(CreateScoreConfigRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get all score configs
   */
  public CompletableFuture<ScoreConfigs> get() {
    return this.rawClient.get().thenApply(response -> response.body());
  }

  /**
   * Get all score configs
   */
  public CompletableFuture<ScoreConfigs> get(RequestOptions requestOptions) {
    return this.rawClient.get(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get all score configs
   */
  public CompletableFuture<ScoreConfigs> get(GetScoreConfigsRequest request) {
    return this.rawClient.get(request).thenApply(response -> response.body());
  }

  /**
   * Get all score configs
   */
  public CompletableFuture<ScoreConfigs> get(GetScoreConfigsRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.get(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get a score config
   */
  public CompletableFuture<ScoreConfig> getById(String configId) {
    return this.rawClient.getById(configId).thenApply(response -> response.body());
  }

  /**
   * Get a score config
   */
  public CompletableFuture<ScoreConfig> getById(String configId, RequestOptions requestOptions) {
    return this.rawClient.getById(configId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Update a score config
   */
  public CompletableFuture<ScoreConfig> update(String configId) {
    return this.rawClient.update(configId).thenApply(response -> response.body());
  }

  /**
   * Update a score config
   */
  public CompletableFuture<ScoreConfig> update(String configId, RequestOptions requestOptions) {
    return this.rawClient.update(configId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Update a score config
   */
  public CompletableFuture<ScoreConfig> update(String configId, UpdateScoreConfigRequest request) {
    return this.rawClient.update(configId, request).thenApply(response -> response.body());
  }

  /**
   * Update a score config
   */
  public CompletableFuture<ScoreConfig> update(String configId, UpdateScoreConfigRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.update(configId, request, requestOptions).thenApply(response -> response.body());
  }
}
