/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client.resources.prompts;

import com.fasterxml.jackson.core.JsonProcessingException;
import ai.proofstate.client.core.ClientOptions;
import ai.proofstate.client.core.ProofStateClientApiException;
import ai.proofstate.client.core.ProofStateClientException;
import ai.proofstate.client.core.ProofStateClientHttpResponse;
import ai.proofstate.client.core.MediaTypes;
import ai.proofstate.client.core.ObjectMappers;
import ai.proofstate.client.core.QueryStringMapper;
import ai.proofstate.client.core.RequestOptions;
import java.io.IOException;
import java.lang.Object;
import java.lang.String;
import java.lang.Void;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import ai.proofstate.client.resources.commons.errors.AccessDeniedError;
import ai.proofstate.client.resources.commons.errors.Error;
import ai.proofstate.client.resources.commons.errors.MethodNotAllowedError;
import ai.proofstate.client.resources.commons.errors.NotFoundError;
import ai.proofstate.client.resources.commons.errors.UnauthorizedError;
import ai.proofstate.client.resources.prompts.requests.DeletePromptRequest;
import ai.proofstate.client.resources.prompts.requests.GetPromptRequest;
import ai.proofstate.client.resources.prompts.requests.ListPromptsMetaRequest;
import ai.proofstate.client.resources.prompts.types.CreatePromptRequest;
import ai.proofstate.client.resources.prompts.types.Prompt;
import ai.proofstate.client.resources.prompts.types.PromptMetaListResponse;

public class RawPromptsClient {
  protected final ClientOptions clientOptions;

  public RawPromptsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Get a prompt
   */
  public ProofStateClientHttpResponse<Prompt> get(String promptName) {
    return get(promptName,GetPromptRequest.builder().build());
  }

  /**
   * Get a prompt
   */
  public ProofStateClientHttpResponse<Prompt> get(String promptName, RequestOptions requestOptions) {
    return get(promptName,GetPromptRequest.builder().build(),requestOptions);
  }

  /**
   * Get a prompt
   */
  public ProofStateClientHttpResponse<Prompt> get(String promptName, GetPromptRequest request) {
    return get(promptName,request,null);
  }

  /**
   * Get a prompt
   */
  public ProofStateClientHttpResponse<Prompt> get(String promptName, GetPromptRequest request,
      RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
      .addPathSegments("api/public/v2")
      .addPathSegments("prompts")
      .addPathSegment(promptName);if (request.getVersion().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "version", request.getVersion().get(), false);
      }
      if (request.getLabel().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "label", request.getLabel().get(), false);
      }
      if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        if (response.isSuccessful()) {
          return new ProofStateClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Prompt.class), response);
        }
        try {
          switch (response.code()) {
            case 400:throw new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            case 403:throw new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            case 405:throw new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
          }
        }
        catch (JsonProcessingException ignored) {
          // unable to map error response, throwing generic error
        }
        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
        throw new ProofStateClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
      }
      catch (IOException e) {
        throw new ProofStateClientException("Network error executing HTTP request", e);
      }
    }

    /**
     * Get a list of prompt names with versions and labels
     */
    public ProofStateClientHttpResponse<PromptMetaListResponse> list() {
      return list(ListPromptsMetaRequest.builder().build());
    }

    /**
     * Get a list of prompt names with versions and labels
     */
    public ProofStateClientHttpResponse<PromptMetaListResponse> list(RequestOptions requestOptions) {
      return list(ListPromptsMetaRequest.builder().build(),requestOptions);
    }

    /**
     * Get a list of prompt names with versions and labels
     */
    public ProofStateClientHttpResponse<PromptMetaListResponse> list(ListPromptsMetaRequest request) {
      return list(request,null);
    }

    /**
     * Get a list of prompt names with versions and labels
     */
    public ProofStateClientHttpResponse<PromptMetaListResponse> list(ListPromptsMetaRequest request,
        RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
        .addPathSegments("api/public/v2")
        .addPathSegments("prompts");if (request.getName().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "name", request.getName().get(), false);
        }
        if (request.getLabel().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "label", request.getLabel().get(), false);
        }
        if (request.getTag().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "tag", request.getTag().get(), false);
        }
        if (request.getPage().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "page", request.getPage().get(), false);
        }
        if (request.getLimit().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "limit", request.getLimit().get(), false);
        }
        if (request.getFromUpdatedAt().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "fromUpdatedAt", request.getFromUpdatedAt().get(), false);
        }
        if (request.getToUpdatedAt().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "toUpdatedAt", request.getToUpdatedAt().get(), false);
        }
        if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
          ResponseBody responseBody = response.body();
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          if (response.isSuccessful()) {
            return new ProofStateClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PromptMetaListResponse.class), response);
          }
          try {
            switch (response.code()) {
              case 400:throw new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
              case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
              case 403:throw new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
              case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
              case 405:throw new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            }
          }
          catch (JsonProcessingException ignored) {
            // unable to map error response, throwing generic error
          }
          Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
          throw new ProofStateClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
        }
        catch (IOException e) {
          throw new ProofStateClientException("Network error executing HTTP request", e);
        }
      }

      /**
       * Create a new version for the prompt with the given <code>name</code>
       */
      public ProofStateClientHttpResponse<Prompt> create(CreatePromptRequest request) {
        return create(request,null);
      }

      /**
       * Create a new version for the prompt with the given <code>name</code>
       */
      public ProofStateClientHttpResponse<Prompt> create(CreatePromptRequest request,
          RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
          .addPathSegments("api/public/v2")
          .addPathSegments("prompts");if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
              httpUrl.addQueryParameter(_key, _value);
            } );
          }
          RequestBody body;
          try {
            body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
          }
          catch(JsonProcessingException e) {
            throw new ProofStateClientException("Failed to serialize request", e);
          }
          Request okhttpRequest = new Request.Builder()
            .url(httpUrl.build())
            .method("POST", body)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Content-Type", "application/json")
            .addHeader("Accept", "application/json")
            .build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              return new ProofStateClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Prompt.class), response);
            }
            try {
              switch (response.code()) {
                case 400:throw new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                case 403:throw new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                case 405:throw new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ProofStateClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
          }
          catch (IOException e) {
            throw new ProofStateClientException("Network error executing HTTP request", e);
          }
        }

        /**
         * Delete prompt versions. If neither version nor label is specified, all versions of the prompt are deleted.
         */
        public ProofStateClientHttpResponse<Void> delete(String promptName) {
          return delete(promptName,DeletePromptRequest.builder().build());
        }

        /**
         * Delete prompt versions. If neither version nor label is specified, all versions of the prompt are deleted.
         */
        public ProofStateClientHttpResponse<Void> delete(String promptName,
            RequestOptions requestOptions) {
          return delete(promptName,DeletePromptRequest.builder().build(),requestOptions);
        }

        /**
         * Delete prompt versions. If neither version nor label is specified, all versions of the prompt are deleted.
         */
        public ProofStateClientHttpResponse<Void> delete(String promptName,
            DeletePromptRequest request) {
          return delete(promptName,request,null);
        }

        /**
         * Delete prompt versions. If neither version nor label is specified, all versions of the prompt are deleted.
         */
        public ProofStateClientHttpResponse<Void> delete(String promptName,
            DeletePromptRequest request, RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
            .addPathSegments("api/public/v2")
            .addPathSegments("prompts")
            .addPathSegment(promptName);if (request.getLabel().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "label", request.getLabel().get(), false);
            }
            if (request.getVersion().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "version", request.getVersion().get(), false);
            }
            if (requestOptions != null) {
              requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
              } );
            }
            Request.Builder _requestBuilder = new Request.Builder()
              .url(httpUrl.build())
              .method("DELETE", null)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Accept", "application/json");
            Request okhttpRequest = _requestBuilder.build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            try (Response response = client.newCall(okhttpRequest).execute()) {
              ResponseBody responseBody = response.body();
              if (response.isSuccessful()) {
                return new ProofStateClientHttpResponse<>(null, response);
              }
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              try {
                switch (response.code()) {
                  case 400:throw new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                  case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                  case 403:throw new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                  case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                  case 405:throw new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
              throw new ProofStateClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
            }
            catch (IOException e) {
              throw new ProofStateClientException("Network error executing HTTP request", e);
            }
          }
        }
