/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client;

import ai.proofstate.client.core.ClientOptions;
import ai.proofstate.client.core.Suppliers;
import java.util.function.Supplier;
import ai.proofstate.client.resources.annotationqueues.AnnotationQueuesClient;
import ai.proofstate.client.resources.blobstorageintegrations.BlobStorageIntegrationsClient;
import ai.proofstate.client.resources.comments.CommentsClient;
import ai.proofstate.client.resources.datasetitems.DatasetItemsClient;
import ai.proofstate.client.resources.datasets.DatasetsClient;
import ai.proofstate.client.resources.health.HealthClient;
import ai.proofstate.client.resources.llmconnections.LlmConnectionsClient;
import ai.proofstate.client.resources.media.MediaClient;
import ai.proofstate.client.resources.metricsv2.MetricsV2Client;
import ai.proofstate.client.resources.models.ModelsClient;
import ai.proofstate.client.resources.observationsv2.ObservationsV2Client;
import ai.proofstate.client.resources.opentelemetry.OpentelemetryClient;
import ai.proofstate.client.resources.organizations.OrganizationsClient;
import ai.proofstate.client.resources.projects.ProjectsClient;
import ai.proofstate.client.resources.prompts.PromptsClient;
import ai.proofstate.client.resources.promptversion.PromptVersionClient;
import ai.proofstate.client.resources.scim.ScimClient;
import ai.proofstate.client.resources.score.ScoreClient;
import ai.proofstate.client.resources.scoreconfigs.ScoreConfigsClient;
import ai.proofstate.client.resources.trace.TraceClient;

public class ProofStateClient {
  protected final ClientOptions clientOptions;

  protected final Supplier<AnnotationQueuesClient> annotationQueuesClient;

  protected final Supplier<BlobStorageIntegrationsClient> blobStorageIntegrationsClient;

  protected final Supplier<CommentsClient> commentsClient;

  protected final Supplier<DatasetItemsClient> datasetItemsClient;

  protected final Supplier<DatasetsClient> datasetsClient;

  protected final Supplier<HealthClient> healthClient;

  protected final Supplier<LlmConnectionsClient> llmConnectionsClient;

  protected final Supplier<MediaClient> mediaClient;

  protected final Supplier<MetricsV2Client> metricsV2Client;

  protected final Supplier<ModelsClient> modelsClient;

  protected final Supplier<ObservationsV2Client> observationsV2Client;

  protected final Supplier<OpentelemetryClient> opentelemetryClient;

  protected final Supplier<OrganizationsClient> organizationsClient;

  protected final Supplier<ProjectsClient> projectsClient;

  protected final Supplier<PromptVersionClient> promptVersionClient;

  protected final Supplier<PromptsClient> promptsClient;

  protected final Supplier<ScimClient> scimClient;

  protected final Supplier<ScoreConfigsClient> scoreConfigsClient;

  protected final Supplier<ScoreClient> scoreClient;

  protected final Supplier<TraceClient> traceClient;

  public ProofStateClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.annotationQueuesClient = Suppliers.memoize(() -> new AnnotationQueuesClient(clientOptions));
    this.blobStorageIntegrationsClient = Suppliers.memoize(() -> new BlobStorageIntegrationsClient(clientOptions));
    this.commentsClient = Suppliers.memoize(() -> new CommentsClient(clientOptions));
    this.datasetItemsClient = Suppliers.memoize(() -> new DatasetItemsClient(clientOptions));
    this.datasetsClient = Suppliers.memoize(() -> new DatasetsClient(clientOptions));
    this.healthClient = Suppliers.memoize(() -> new HealthClient(clientOptions));
    this.llmConnectionsClient = Suppliers.memoize(() -> new LlmConnectionsClient(clientOptions));
    this.mediaClient = Suppliers.memoize(() -> new MediaClient(clientOptions));
    this.metricsV2Client = Suppliers.memoize(() -> new MetricsV2Client(clientOptions));
    this.modelsClient = Suppliers.memoize(() -> new ModelsClient(clientOptions));
    this.observationsV2Client = Suppliers.memoize(() -> new ObservationsV2Client(clientOptions));
    this.opentelemetryClient = Suppliers.memoize(() -> new OpentelemetryClient(clientOptions));
    this.organizationsClient = Suppliers.memoize(() -> new OrganizationsClient(clientOptions));
    this.projectsClient = Suppliers.memoize(() -> new ProjectsClient(clientOptions));
    this.promptVersionClient = Suppliers.memoize(() -> new PromptVersionClient(clientOptions));
    this.promptsClient = Suppliers.memoize(() -> new PromptsClient(clientOptions));
    this.scimClient = Suppliers.memoize(() -> new ScimClient(clientOptions));
    this.scoreConfigsClient = Suppliers.memoize(() -> new ScoreConfigsClient(clientOptions));
    this.scoreClient = Suppliers.memoize(() -> new ScoreClient(clientOptions));
    this.traceClient = Suppliers.memoize(() -> new TraceClient(clientOptions));
  }

  public AnnotationQueuesClient annotationQueues() {
    return this.annotationQueuesClient.get();
  }

  public BlobStorageIntegrationsClient blobStorageIntegrations() {
    return this.blobStorageIntegrationsClient.get();
  }

  public CommentsClient comments() {
    return this.commentsClient.get();
  }

  public DatasetItemsClient datasetItems() {
    return this.datasetItemsClient.get();
  }

  public DatasetsClient datasets() {
    return this.datasetsClient.get();
  }

  public HealthClient health() {
    return this.healthClient.get();
  }

  public LlmConnectionsClient llmConnections() {
    return this.llmConnectionsClient.get();
  }

  public MediaClient media() {
    return this.mediaClient.get();
  }

  public MetricsV2Client metricsV2() {
    return this.metricsV2Client.get();
  }

  public ModelsClient models() {
    return this.modelsClient.get();
  }

  public ObservationsV2Client observationsV2() {
    return this.observationsV2Client.get();
  }

  public OpentelemetryClient opentelemetry() {
    return this.opentelemetryClient.get();
  }

  public OrganizationsClient organizations() {
    return this.organizationsClient.get();
  }

  public ProjectsClient projects() {
    return this.projectsClient.get();
  }

  public PromptVersionClient promptVersion() {
    return this.promptVersionClient.get();
  }

  public PromptsClient prompts() {
    return this.promptsClient.get();
  }

  public ScimClient scim() {
    return this.scimClient.get();
  }

  public ScoreConfigsClient scoreConfigs() {
    return this.scoreConfigsClient.get();
  }

  public ScoreClient score() {
    return this.scoreClient.get();
  }

  public TraceClient trace() {
    return this.traceClient.get();
  }

  public static ProofStateClientBuilder builder() {
    return new ProofStateClientBuilder();
  }
}
