/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client.analytics.resources.scoresv3.types;

import ai.proofstate.client.analytics.resources.commons.types.ScoreSource;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.Map;
import java.util.Optional;

public interface IBaseScoreV3 {
  String getId();

  String getProjectId();

  String getName();

  ScoreSource getSource();

  OffsetDateTime getTimestamp();

  String getEnvironment();

  OffsetDateTime getCreatedAt();

  OffsetDateTime getUpdatedAt();

  Optional<String> getComment();

  Optional<String> getConfigId();

  Optional<Map<String, Object>> getMetadata();

  Optional<String> getAuthorUserId();

  Optional<String> getQueueId();

  Optional<ScoreSubjectV3> getSubject();
}
