/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client.analytics.resources.scoresv3;

import ai.proofstate.client.analytics.core.ClientOptions;
import ai.proofstate.client.analytics.core.ObjectMappers;
import ai.proofstate.client.analytics.core.ProofStateAnalyticsClientApiException;
import ai.proofstate.client.analytics.core.ProofStateAnalyticsClientException;
import ai.proofstate.client.analytics.core.ProofStateAnalyticsClientHttpResponse;
import ai.proofstate.client.analytics.core.QueryStringMapper;
import ai.proofstate.client.analytics.core.RequestOptions;
import ai.proofstate.client.analytics.resources.commons.errors.AccessDeniedError;
import ai.proofstate.client.analytics.resources.commons.errors.Error;
import ai.proofstate.client.analytics.resources.commons.errors.MethodNotAllowedError;
import ai.proofstate.client.analytics.resources.commons.errors.NotFoundError;
import ai.proofstate.client.analytics.resources.commons.errors.UnauthorizedError;
import ai.proofstate.client.analytics.resources.scoresv3.requests.GetScoresV3Request;
import ai.proofstate.client.analytics.resources.scoresv3.types.GetScoresV3Response;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.lang.Object;
import java.lang.String;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawScoresV3Client {
  protected final ClientOptions clientOptions;

  public RawScoresV3Client(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Get a list of scores with a polymorphic <code>value</code> field (v3).
   * <p>The <code>value</code> field type depends on <code>dataType</code>:</p>
   * <ul>
   * <li><code>NUMERIC</code> → number</li>
   * <li><code>BOOLEAN</code> → boolean</li>
   * <li><code>CATEGORICAL</code>, <code>TEXT</code>, <code>CORRECTION</code> → string</li>
   * </ul>
   * <p>The response always includes the core fields: id, projectId, name,
   * value, dataType, source, timestamp, environment, createdAt, updatedAt.</p>
   * <p>Additional field groups can be requested via the <code>fields</code> parameter:</p>
   * <ul>
   * <li><code>details</code> — adds comment, configId, metadata</li>
   * <li><code>subject</code> — adds the subject object describing the entity the score
   * is attached to: kind (trace, observation, session, or experiment),
   * id, and traceId for observation-level scores</li>
   * <li><code>annotation</code> — adds authorUserId, queueId</li>
   * </ul>
   * <p>Unknown group names return HTTP 400.</p>
   */
  public ProofStateAnalyticsClientHttpResponse<GetScoresV3Response> getManyV3() {
    return getManyV3(GetScoresV3Request.builder().build());
  }

  /**
   * Get a list of scores with a polymorphic <code>value</code> field (v3).
   * <p>The <code>value</code> field type depends on <code>dataType</code>:</p>
   * <ul>
   * <li><code>NUMERIC</code> → number</li>
   * <li><code>BOOLEAN</code> → boolean</li>
   * <li><code>CATEGORICAL</code>, <code>TEXT</code>, <code>CORRECTION</code> → string</li>
   * </ul>
   * <p>The response always includes the core fields: id, projectId, name,
   * value, dataType, source, timestamp, environment, createdAt, updatedAt.</p>
   * <p>Additional field groups can be requested via the <code>fields</code> parameter:</p>
   * <ul>
   * <li><code>details</code> — adds comment, configId, metadata</li>
   * <li><code>subject</code> — adds the subject object describing the entity the score
   * is attached to: kind (trace, observation, session, or experiment),
   * id, and traceId for observation-level scores</li>
   * <li><code>annotation</code> — adds authorUserId, queueId</li>
   * </ul>
   * <p>Unknown group names return HTTP 400.</p>
   */
  public ProofStateAnalyticsClientHttpResponse<GetScoresV3Response> getManyV3(
      RequestOptions requestOptions) {
    return getManyV3(GetScoresV3Request.builder().build(),requestOptions);
  }

  /**
   * Get a list of scores with a polymorphic <code>value</code> field (v3).
   * <p>The <code>value</code> field type depends on <code>dataType</code>:</p>
   * <ul>
   * <li><code>NUMERIC</code> → number</li>
   * <li><code>BOOLEAN</code> → boolean</li>
   * <li><code>CATEGORICAL</code>, <code>TEXT</code>, <code>CORRECTION</code> → string</li>
   * </ul>
   * <p>The response always includes the core fields: id, projectId, name,
   * value, dataType, source, timestamp, environment, createdAt, updatedAt.</p>
   * <p>Additional field groups can be requested via the <code>fields</code> parameter:</p>
   * <ul>
   * <li><code>details</code> — adds comment, configId, metadata</li>
   * <li><code>subject</code> — adds the subject object describing the entity the score
   * is attached to: kind (trace, observation, session, or experiment),
   * id, and traceId for observation-level scores</li>
   * <li><code>annotation</code> — adds authorUserId, queueId</li>
   * </ul>
   * <p>Unknown group names return HTTP 400.</p>
   */
  public ProofStateAnalyticsClientHttpResponse<GetScoresV3Response> getManyV3(
      GetScoresV3Request request) {
    return getManyV3(request,null);
  }

  /**
   * Get a list of scores with a polymorphic <code>value</code> field (v3).
   * <p>The <code>value</code> field type depends on <code>dataType</code>:</p>
   * <ul>
   * <li><code>NUMERIC</code> → number</li>
   * <li><code>BOOLEAN</code> → boolean</li>
   * <li><code>CATEGORICAL</code>, <code>TEXT</code>, <code>CORRECTION</code> → string</li>
   * </ul>
   * <p>The response always includes the core fields: id, projectId, name,
   * value, dataType, source, timestamp, environment, createdAt, updatedAt.</p>
   * <p>Additional field groups can be requested via the <code>fields</code> parameter:</p>
   * <ul>
   * <li><code>details</code> — adds comment, configId, metadata</li>
   * <li><code>subject</code> — adds the subject object describing the entity the score
   * is attached to: kind (trace, observation, session, or experiment),
   * id, and traceId for observation-level scores</li>
   * <li><code>annotation</code> — adds authorUserId, queueId</li>
   * </ul>
   * <p>Unknown group names return HTTP 400.</p>
   */
  public ProofStateAnalyticsClientHttpResponse<GetScoresV3Response> getManyV3(
      GetScoresV3Request request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
      .addPathSegments("api/public")
      .addPathSegments("v3/scores");if (request.getLimit().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "limit", request.getLimit().get(), false);
      }
      if (request.getCursor().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "cursor", request.getCursor().get(), false);
      }
      if (request.getFields().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "fields", request.getFields().get(), false);
      }
      if (request.getId().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "id", request.getId().get(), false);
      }
      if (request.getName().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "name", request.getName().get(), false);
      }
      if (request.getSource().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "source", request.getSource().get(), false);
      }
      if (request.getDataType().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "dataType", request.getDataType().get(), false);
      }
      if (request.getEnvironment().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "environment", request.getEnvironment().get(), false);
      }
      if (request.getConfigId().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "configId", request.getConfigId().get(), false);
      }
      if (request.getQueueId().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "queueId", request.getQueueId().get(), false);
      }
      if (request.getAuthorUserId().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "authorUserId", request.getAuthorUserId().get(), false);
      }
      if (request.getValue().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "value", request.getValue().get(), false);
      }
      if (request.getValueMin().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "valueMin", request.getValueMin().get(), false);
      }
      if (request.getValueMax().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "valueMax", request.getValueMax().get(), false);
      }
      if (request.getTraceId().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "traceId", request.getTraceId().get(), false);
      }
      if (request.getSessionId().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "sessionId", request.getSessionId().get(), false);
      }
      if (request.getObservationId().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "observationId", request.getObservationId().get(), false);
      }
      if (request.getExperimentId().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "experimentId", request.getExperimentId().get(), false);
      }
      if (request.getFromTimestamp().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "fromTimestamp", request.getFromTimestamp().get(), false);
      }
      if (request.getToTimestamp().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "toTimestamp", request.getToTimestamp().get(), false);
      }
      if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        if (response.isSuccessful()) {
          return new ProofStateAnalyticsClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, GetScoresV3Response.class), response);
        }
        try {
          switch (response.code()) {
            case 400:throw new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            case 403:throw new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            case 405:throw new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
          }
        }
        catch (JsonProcessingException ignored) {
          // unable to map error response, throwing generic error
        }
        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
        throw new ProofStateAnalyticsClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
      }
      catch (IOException e) {
        throw new ProofStateAnalyticsClientException("Network error executing HTTP request", e);
      }
    }
  }
