/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client.resources.promptversion;

import ai.proofstate.client.core.ClientOptions;
import ai.proofstate.client.core.RequestOptions;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import ai.proofstate.client.resources.prompts.types.Prompt;
import ai.proofstate.client.resources.promptversion.requests.UpdatePromptRequest;

public class AsyncPromptVersionClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawPromptVersionClient rawClient;

  public AsyncPromptVersionClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawPromptVersionClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawPromptVersionClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Update labels for a specific prompt version
   */
  public CompletableFuture<Prompt> update(String name, int version, UpdatePromptRequest request) {
    return this.rawClient.update(name, version, request).thenApply(response -> response.body());
  }

  /**
   * Update labels for a specific prompt version
   */
  public CompletableFuture<Prompt> update(String name, int version, UpdatePromptRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.update(name, version, request, requestOptions).thenApply(response -> response.body());
  }
}
