/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client.analytics.core;

import java.lang.Integer;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.TimeUnit;
import java.util.function.Supplier;

public final class RequestOptions {
  private final String xProofStateSdkName;

  private final String xProofStateSdkVersion;

  private final String xProofStatePublicKey;

  private final Optional<Integer> timeout;

  private final TimeUnit timeoutTimeUnit;

  private final Map<String, String> headers;

  private final Map<String, Supplier<String>> headerSuppliers;

  private final Map<String, String> queryParameters;

  private final Map<String, Supplier<String>> queryParameterSuppliers;

  private RequestOptions(String xProofStateSdkName, String xProofStateSdkVersion,
      String xProofStatePublicKey, Optional<Integer> timeout, TimeUnit timeoutTimeUnit,
      Map<String, String> headers, Map<String, Supplier<String>> headerSuppliers,
      Map<String, String> queryParameters, Map<String, Supplier<String>> queryParameterSuppliers) {
    this.xProofStateSdkName = xProofStateSdkName;
    this.xProofStateSdkVersion = xProofStateSdkVersion;
    this.xProofStatePublicKey = xProofStatePublicKey;
    this.timeout = timeout;
    this.timeoutTimeUnit = timeoutTimeUnit;
    this.headers = headers;
    this.headerSuppliers = headerSuppliers;
    this.queryParameters = queryParameters;
    this.queryParameterSuppliers = queryParameterSuppliers;
  }

  public Optional<Integer> getTimeout() {
    return timeout;
  }

  public TimeUnit getTimeoutTimeUnit() {
    return timeoutTimeUnit;
  }

  public Map<String, String> getHeaders() {
    Map<String, String> headers = new HashMap<>();
    if (this.xProofStateSdkName != null) {
      headers.put("X-ProofState-Sdk-Name", this.xProofStateSdkName);
    }
    if (this.xProofStateSdkVersion != null) {
      headers.put("X-ProofState-Sdk-Version", this.xProofStateSdkVersion);
    }
    if (this.xProofStatePublicKey != null) {
      headers.put("X-ProofState-Public-Key", this.xProofStatePublicKey);
    }
    headers.putAll(this.headers);
    this.headerSuppliers.forEach((key, supplier) ->  {
      headers.put(key, supplier.get());
    } );
    return headers;
  }

  public Map<String, String> getQueryParameters() {
    Map<String, String> queryParameters = new HashMap<>(this.queryParameters);
    this.queryParameterSuppliers.forEach((key, supplier) ->  {
      queryParameters.put(key, supplier.get());
    } );
    return queryParameters;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static class Builder {
    private String xProofStateSdkName = null;

    private String xProofStateSdkVersion = null;

    private String xProofStatePublicKey = null;

    private Optional<Integer> timeout = Optional.empty();

    private TimeUnit timeoutTimeUnit = TimeUnit.SECONDS;

    private final Map<String, String> headers = new HashMap<>();

    private final Map<String, Supplier<String>> headerSuppliers = new HashMap<>();

    private final Map<String, String> queryParameters = new HashMap<>();

    private final Map<String, Supplier<String>> queryParameterSuppliers = new HashMap<>();

    public Builder xProofStateSdkName(String xProofStateSdkName) {
      this.xProofStateSdkName = xProofStateSdkName;
      return this;
    }

    public Builder xProofStateSdkVersion(String xProofStateSdkVersion) {
      this.xProofStateSdkVersion = xProofStateSdkVersion;
      return this;
    }

    public Builder xProofStatePublicKey(String xProofStatePublicKey) {
      this.xProofStatePublicKey = xProofStatePublicKey;
      return this;
    }

    public Builder timeout(Integer timeout) {
      this.timeout = Optional.of(timeout);
      return this;
    }

    public Builder timeout(Integer timeout, TimeUnit timeoutTimeUnit) {
      this.timeout = Optional.of(timeout);
      this.timeoutTimeUnit = timeoutTimeUnit;
      return this;
    }

    public Builder addHeader(String key, String value) {
      this.headers.put(key, value);
      return this;
    }

    public Builder addHeader(String key, Supplier<String> value) {
      this.headerSuppliers.put(key, value);
      return this;
    }

    public Builder addQueryParameter(String key, String value) {
      this.queryParameters.put(key, value);
      return this;
    }

    public Builder addQueryParameter(String key, Supplier<String> value) {
      this.queryParameterSuppliers.put(key, value);
      return this;
    }

    public RequestOptions build() {
      return new RequestOptions(xProofStateSdkName, xProofStateSdkVersion, xProofStatePublicKey, timeout, timeoutTimeUnit, headers, headerSuppliers, queryParameters, queryParameterSuppliers);
    }
  }
}
