/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.proofstate.client.resources.annotationqueues;

import com.fasterxml.jackson.core.JsonProcessingException;
import ai.proofstate.client.core.ClientOptions;
import ai.proofstate.client.core.ProofStateClientApiException;
import ai.proofstate.client.core.ProofStateClientException;
import ai.proofstate.client.core.ProofStateClientHttpResponse;
import ai.proofstate.client.core.MediaTypes;
import ai.proofstate.client.core.ObjectMappers;
import ai.proofstate.client.core.QueryStringMapper;
import ai.proofstate.client.core.RequestOptions;
import java.io.IOException;
import java.lang.Object;
import java.lang.String;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import ai.proofstate.client.resources.annotationqueues.requests.GetAnnotationQueueItemsRequest;
import ai.proofstate.client.resources.annotationqueues.requests.GetAnnotationQueuesRequest;
import ai.proofstate.client.resources.annotationqueues.types.AnnotationQueue;
import ai.proofstate.client.resources.annotationqueues.types.AnnotationQueueAssignmentRequest;
import ai.proofstate.client.resources.annotationqueues.types.AnnotationQueueItem;
import ai.proofstate.client.resources.annotationqueues.types.CreateAnnotationQueueAssignmentResponse;
import ai.proofstate.client.resources.annotationqueues.types.CreateAnnotationQueueItemRequest;
import ai.proofstate.client.resources.annotationqueues.types.CreateAnnotationQueueRequest;
import ai.proofstate.client.resources.annotationqueues.types.DeleteAnnotationQueueAssignmentResponse;
import ai.proofstate.client.resources.annotationqueues.types.DeleteAnnotationQueueItemResponse;
import ai.proofstate.client.resources.annotationqueues.types.PaginatedAnnotationQueueItems;
import ai.proofstate.client.resources.annotationqueues.types.PaginatedAnnotationQueues;
import ai.proofstate.client.resources.annotationqueues.types.UpdateAnnotationQueueItemRequest;
import ai.proofstate.client.resources.commons.errors.AccessDeniedError;
import ai.proofstate.client.resources.commons.errors.Error;
import ai.proofstate.client.resources.commons.errors.MethodNotAllowedError;
import ai.proofstate.client.resources.commons.errors.NotFoundError;
import ai.proofstate.client.resources.commons.errors.UnauthorizedError;

public class RawAnnotationQueuesClient {
  protected final ClientOptions clientOptions;

  public RawAnnotationQueuesClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Get all annotation queues
   */
  public ProofStateClientHttpResponse<PaginatedAnnotationQueues> listQueues() {
    return listQueues(GetAnnotationQueuesRequest.builder().build());
  }

  /**
   * Get all annotation queues
   */
  public ProofStateClientHttpResponse<PaginatedAnnotationQueues> listQueues(
      RequestOptions requestOptions) {
    return listQueues(GetAnnotationQueuesRequest.builder().build(),requestOptions);
  }

  /**
   * Get all annotation queues
   */
  public ProofStateClientHttpResponse<PaginatedAnnotationQueues> listQueues(
      GetAnnotationQueuesRequest request) {
    return listQueues(request,null);
  }

  /**
   * Get all annotation queues
   */
  public ProofStateClientHttpResponse<PaginatedAnnotationQueues> listQueues(
      GetAnnotationQueuesRequest request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
      .addPathSegments("api/public")
      .addPathSegments("annotation-queues");if (request.getPage().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "page", request.getPage().get(), false);
      }
      if (request.getLimit().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "limit", request.getLimit().get(), false);
      }
      if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        if (response.isSuccessful()) {
          return new ProofStateClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PaginatedAnnotationQueues.class), response);
        }
        try {
          switch (response.code()) {
            case 400:throw new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            case 403:throw new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            case 405:throw new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
          }
        }
        catch (JsonProcessingException ignored) {
          // unable to map error response, throwing generic error
        }
        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
        throw new ProofStateClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
      }
      catch (IOException e) {
        throw new ProofStateClientException("Network error executing HTTP request", e);
      }
    }

    /**
     * Create an annotation queue
     */
    public ProofStateClientHttpResponse<AnnotationQueue> createQueue(
        CreateAnnotationQueueRequest request) {
      return createQueue(request,null);
    }

    /**
     * Create an annotation queue
     */
    public ProofStateClientHttpResponse<AnnotationQueue> createQueue(
        CreateAnnotationQueueRequest request, RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
        .addPathSegments("api/public")
        .addPathSegments("annotation-queues");if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        RequestBody body;
        try {
          body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        }
        catch(JsonProcessingException e) {
          throw new ProofStateClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
          .url(httpUrl.build())
          .method("POST", body)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json")
          .addHeader("Accept", "application/json")
          .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
          ResponseBody responseBody = response.body();
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          if (response.isSuccessful()) {
            return new ProofStateClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, AnnotationQueue.class), response);
          }
          try {
            switch (response.code()) {
              case 400:throw new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
              case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
              case 403:throw new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
              case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
              case 405:throw new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            }
          }
          catch (JsonProcessingException ignored) {
            // unable to map error response, throwing generic error
          }
          Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
          throw new ProofStateClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
        }
        catch (IOException e) {
          throw new ProofStateClientException("Network error executing HTTP request", e);
        }
      }

      /**
       * Get an annotation queue by ID
       */
      public ProofStateClientHttpResponse<AnnotationQueue> getQueue(String queueId) {
        return getQueue(queueId,null);
      }

      /**
       * Get an annotation queue by ID
       */
      public ProofStateClientHttpResponse<AnnotationQueue> getQueue(String queueId,
          RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
          .addPathSegments("api/public")
          .addPathSegments("annotation-queues")
          .addPathSegment(queueId);if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
              httpUrl.addQueryParameter(_key, _value);
            } );
          }
          Request okhttpRequest = new Request.Builder()
            .url(httpUrl.build())
            .method("GET", null)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Accept", "application/json")
            .build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              return new ProofStateClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, AnnotationQueue.class), response);
            }
            try {
              switch (response.code()) {
                case 400:throw new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                case 403:throw new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                case 405:throw new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ProofStateClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
          }
          catch (IOException e) {
            throw new ProofStateClientException("Network error executing HTTP request", e);
          }
        }

        /**
         * Get items for a specific annotation queue
         */
        public ProofStateClientHttpResponse<PaginatedAnnotationQueueItems> listQueueItems(
            String queueId) {
          return listQueueItems(queueId,GetAnnotationQueueItemsRequest.builder().build());
        }

        /**
         * Get items for a specific annotation queue
         */
        public ProofStateClientHttpResponse<PaginatedAnnotationQueueItems> listQueueItems(
            String queueId, RequestOptions requestOptions) {
          return listQueueItems(queueId,GetAnnotationQueueItemsRequest.builder().build(),requestOptions);
        }

        /**
         * Get items for a specific annotation queue
         */
        public ProofStateClientHttpResponse<PaginatedAnnotationQueueItems> listQueueItems(
            String queueId, GetAnnotationQueueItemsRequest request) {
          return listQueueItems(queueId,request,null);
        }

        /**
         * Get items for a specific annotation queue
         */
        public ProofStateClientHttpResponse<PaginatedAnnotationQueueItems> listQueueItems(
            String queueId, GetAnnotationQueueItemsRequest request, RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
            .addPathSegments("api/public")
            .addPathSegments("annotation-queues")
            .addPathSegment(queueId)
            .addPathSegments("items");if (request.getStatus().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "status", request.getStatus().get(), false);
            }
            if (request.getPage().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "page", request.getPage().get(), false);
            }
            if (request.getLimit().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "limit", request.getLimit().get(), false);
            }
            if (requestOptions != null) {
              requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
              } );
            }
            Request.Builder _requestBuilder = new Request.Builder()
              .url(httpUrl.build())
              .method("GET", null)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Accept", "application/json");
            Request okhttpRequest = _requestBuilder.build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            try (Response response = client.newCall(okhttpRequest).execute()) {
              ResponseBody responseBody = response.body();
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              if (response.isSuccessful()) {
                return new ProofStateClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PaginatedAnnotationQueueItems.class), response);
              }
              try {
                switch (response.code()) {
                  case 400:throw new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                  case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                  case 403:throw new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                  case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                  case 405:throw new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
              throw new ProofStateClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
            }
            catch (IOException e) {
              throw new ProofStateClientException("Network error executing HTTP request", e);
            }
          }

          /**
           * Get a specific item from an annotation queue
           */
          public ProofStateClientHttpResponse<AnnotationQueueItem> getQueueItem(String queueId,
              String itemId) {
            return getQueueItem(queueId,itemId,null);
          }

          /**
           * Get a specific item from an annotation queue
           */
          public ProofStateClientHttpResponse<AnnotationQueueItem> getQueueItem(String queueId,
              String itemId, RequestOptions requestOptions) {
            HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
              .addPathSegments("api/public")
              .addPathSegments("annotation-queues")
              .addPathSegment(queueId)
              .addPathSegments("items")
              .addPathSegment(itemId);if (requestOptions != null) {
                requestOptions.getQueryParameters().forEach((_key, _value) -> {
                  httpUrl.addQueryParameter(_key, _value);
                } );
              }
              Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
              OkHttpClient client = clientOptions.httpClient();
              if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                client = clientOptions.httpClientWithTimeout(requestOptions);
              }
              try (Response response = client.newCall(okhttpRequest).execute()) {
                ResponseBody responseBody = response.body();
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                if (response.isSuccessful()) {
                  return new ProofStateClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, AnnotationQueueItem.class), response);
                }
                try {
                  switch (response.code()) {
                    case 400:throw new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 403:throw new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 405:throw new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                  }
                }
                catch (JsonProcessingException ignored) {
                  // unable to map error response, throwing generic error
                }
                Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                throw new ProofStateClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
              }
              catch (IOException e) {
                throw new ProofStateClientException("Network error executing HTTP request", e);
              }
            }

            /**
             * Add an item to an annotation queue
             */
            public ProofStateClientHttpResponse<AnnotationQueueItem> createQueueItem(String queueId,
                CreateAnnotationQueueItemRequest request) {
              return createQueueItem(queueId,request,null);
            }

            /**
             * Add an item to an annotation queue
             */
            public ProofStateClientHttpResponse<AnnotationQueueItem> createQueueItem(String queueId,
                CreateAnnotationQueueItemRequest request, RequestOptions requestOptions) {
              HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
                .addPathSegments("api/public")
                .addPathSegments("annotation-queues")
                .addPathSegment(queueId)
                .addPathSegments("items");if (requestOptions != null) {
                  requestOptions.getQueryParameters().forEach((_key, _value) -> {
                    httpUrl.addQueryParameter(_key, _value);
                  } );
                }
                RequestBody body;
                try {
                  body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
                }
                catch(JsonProcessingException e) {
                  throw new ProofStateClientException("Failed to serialize request", e);
                }
                Request okhttpRequest = new Request.Builder()
                  .url(httpUrl.build())
                  .method("POST", body)
                  .headers(Headers.of(clientOptions.headers(requestOptions)))
                  .addHeader("Content-Type", "application/json")
                  .addHeader("Accept", "application/json")
                  .build();
                OkHttpClient client = clientOptions.httpClient();
                if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                  client = clientOptions.httpClientWithTimeout(requestOptions);
                }
                try (Response response = client.newCall(okhttpRequest).execute()) {
                  ResponseBody responseBody = response.body();
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  if (response.isSuccessful()) {
                    return new ProofStateClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, AnnotationQueueItem.class), response);
                  }
                  try {
                    switch (response.code()) {
                      case 400:throw new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                      case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                      case 403:throw new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                      case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                      case 405:throw new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    }
                  }
                  catch (JsonProcessingException ignored) {
                    // unable to map error response, throwing generic error
                  }
                  Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                  throw new ProofStateClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
                }
                catch (IOException e) {
                  throw new ProofStateClientException("Network error executing HTTP request", e);
                }
              }

              /**
               * Update an annotation queue item
               */
              public ProofStateClientHttpResponse<AnnotationQueueItem> updateQueueItem(String queueId,
                  String itemId) {
                return updateQueueItem(queueId,itemId,UpdateAnnotationQueueItemRequest.builder().build());
              }

              /**
               * Update an annotation queue item
               */
              public ProofStateClientHttpResponse<AnnotationQueueItem> updateQueueItem(String queueId,
                  String itemId, RequestOptions requestOptions) {
                return updateQueueItem(queueId,itemId,UpdateAnnotationQueueItemRequest.builder().build(),requestOptions);
              }

              /**
               * Update an annotation queue item
               */
              public ProofStateClientHttpResponse<AnnotationQueueItem> updateQueueItem(String queueId,
                  String itemId, UpdateAnnotationQueueItemRequest request) {
                return updateQueueItem(queueId,itemId,request,null);
              }

              /**
               * Update an annotation queue item
               */
              public ProofStateClientHttpResponse<AnnotationQueueItem> updateQueueItem(String queueId,
                  String itemId, UpdateAnnotationQueueItemRequest request,
                  RequestOptions requestOptions) {
                HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
                  .addPathSegments("api/public")
                  .addPathSegments("annotation-queues")
                  .addPathSegment(queueId)
                  .addPathSegments("items")
                  .addPathSegment(itemId);if (requestOptions != null) {
                    requestOptions.getQueryParameters().forEach((_key, _value) -> {
                      httpUrl.addQueryParameter(_key, _value);
                    } );
                  }
                  RequestBody body;
                  try {
                    body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
                  }
                  catch(JsonProcessingException e) {
                    throw new ProofStateClientException("Failed to serialize request", e);
                  }
                  Request okhttpRequest = new Request.Builder()
                    .url(httpUrl.build())
                    .method("PATCH", body)
                    .headers(Headers.of(clientOptions.headers(requestOptions)))
                    .addHeader("Content-Type", "application/json")
                    .addHeader("Accept", "application/json")
                    .build();
                  OkHttpClient client = clientOptions.httpClient();
                  if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                    client = clientOptions.httpClientWithTimeout(requestOptions);
                  }
                  try (Response response = client.newCall(okhttpRequest).execute()) {
                    ResponseBody responseBody = response.body();
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                      return new ProofStateClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, AnnotationQueueItem.class), response);
                    }
                    try {
                      switch (response.code()) {
                        case 400:throw new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                        case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                        case 403:throw new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                        case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                        case 405:throw new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                      }
                    }
                    catch (JsonProcessingException ignored) {
                      // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    throw new ProofStateClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
                  }
                  catch (IOException e) {
                    throw new ProofStateClientException("Network error executing HTTP request", e);
                  }
                }

                /**
                 * Remove an item from an annotation queue
                 */
                public ProofStateClientHttpResponse<DeleteAnnotationQueueItemResponse> deleteQueueItem(
                    String queueId, String itemId) {
                  return deleteQueueItem(queueId,itemId,null);
                }

                /**
                 * Remove an item from an annotation queue
                 */
                public ProofStateClientHttpResponse<DeleteAnnotationQueueItemResponse> deleteQueueItem(
                    String queueId, String itemId, RequestOptions requestOptions) {
                  HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
                    .addPathSegments("api/public")
                    .addPathSegments("annotation-queues")
                    .addPathSegment(queueId)
                    .addPathSegments("items")
                    .addPathSegment(itemId);if (requestOptions != null) {
                      requestOptions.getQueryParameters().forEach((_key, _value) -> {
                        httpUrl.addQueryParameter(_key, _value);
                      } );
                    }
                    Request okhttpRequest = new Request.Builder()
                      .url(httpUrl.build())
                      .method("DELETE", null)
                      .headers(Headers.of(clientOptions.headers(requestOptions)))
                      .addHeader("Accept", "application/json")
                      .build();
                    OkHttpClient client = clientOptions.httpClient();
                    if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                      client = clientOptions.httpClientWithTimeout(requestOptions);
                    }
                    try (Response response = client.newCall(okhttpRequest).execute()) {
                      ResponseBody responseBody = response.body();
                      String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                      if (response.isSuccessful()) {
                        return new ProofStateClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, DeleteAnnotationQueueItemResponse.class), response);
                      }
                      try {
                        switch (response.code()) {
                          case 400:throw new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                          case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                          case 403:throw new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                          case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                          case 405:throw new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                        }
                      }
                      catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                      }
                      Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                      throw new ProofStateClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
                    }
                    catch (IOException e) {
                      throw new ProofStateClientException("Network error executing HTTP request", e);
                    }
                  }

                  /**
                   * Create an assignment for a user to an annotation queue
                   */
                  public ProofStateClientHttpResponse<CreateAnnotationQueueAssignmentResponse> createQueueAssignment(
                      String queueId, AnnotationQueueAssignmentRequest request) {
                    return createQueueAssignment(queueId,request,null);
                  }

                  /**
                   * Create an assignment for a user to an annotation queue
                   */
                  public ProofStateClientHttpResponse<CreateAnnotationQueueAssignmentResponse> createQueueAssignment(
                      String queueId, AnnotationQueueAssignmentRequest request,
                      RequestOptions requestOptions) {
                    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
                      .addPathSegments("api/public")
                      .addPathSegments("annotation-queues")
                      .addPathSegment(queueId)
                      .addPathSegments("assignments");if (requestOptions != null) {
                        requestOptions.getQueryParameters().forEach((_key, _value) -> {
                          httpUrl.addQueryParameter(_key, _value);
                        } );
                      }
                      RequestBody body;
                      try {
                        body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
                      }
                      catch(JsonProcessingException e) {
                        throw new ProofStateClientException("Failed to serialize request", e);
                      }
                      Request okhttpRequest = new Request.Builder()
                        .url(httpUrl.build())
                        .method("POST", body)
                        .headers(Headers.of(clientOptions.headers(requestOptions)))
                        .addHeader("Content-Type", "application/json")
                        .addHeader("Accept", "application/json")
                        .build();
                      OkHttpClient client = clientOptions.httpClient();
                      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                        client = clientOptions.httpClientWithTimeout(requestOptions);
                      }
                      try (Response response = client.newCall(okhttpRequest).execute()) {
                        ResponseBody responseBody = response.body();
                        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                        if (response.isSuccessful()) {
                          return new ProofStateClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CreateAnnotationQueueAssignmentResponse.class), response);
                        }
                        try {
                          switch (response.code()) {
                            case 400:throw new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                            case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                            case 403:throw new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                            case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                            case 405:throw new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                          }
                        }
                        catch (JsonProcessingException ignored) {
                          // unable to map error response, throwing generic error
                        }
                        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                        throw new ProofStateClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
                      }
                      catch (IOException e) {
                        throw new ProofStateClientException("Network error executing HTTP request", e);
                      }
                    }

                    /**
                     * Delete an assignment for a user to an annotation queue
                     */
                    public ProofStateClientHttpResponse<DeleteAnnotationQueueAssignmentResponse> deleteQueueAssignment(
                        String queueId, AnnotationQueueAssignmentRequest request) {
                      return deleteQueueAssignment(queueId,request,null);
                    }

                    /**
                     * Delete an assignment for a user to an annotation queue
                     */
                    public ProofStateClientHttpResponse<DeleteAnnotationQueueAssignmentResponse> deleteQueueAssignment(
                        String queueId, AnnotationQueueAssignmentRequest request,
                        RequestOptions requestOptions) {
                      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
                        .addPathSegments("api/public")
                        .addPathSegments("annotation-queues")
                        .addPathSegment(queueId)
                        .addPathSegments("assignments");if (requestOptions != null) {
                          requestOptions.getQueryParameters().forEach((_key, _value) -> {
                            httpUrl.addQueryParameter(_key, _value);
                          } );
                        }
                        RequestBody body;
                        try {
                          body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
                        }
                        catch(JsonProcessingException e) {
                          throw new ProofStateClientException("Failed to serialize request", e);
                        }
                        Request okhttpRequest = new Request.Builder()
                          .url(httpUrl.build())
                          .method("DELETE", body)
                          .headers(Headers.of(clientOptions.headers(requestOptions)))
                          .addHeader("Content-Type", "application/json")
                          .addHeader("Accept", "application/json")
                          .build();
                        OkHttpClient client = clientOptions.httpClient();
                        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                          client = clientOptions.httpClientWithTimeout(requestOptions);
                        }
                        try (Response response = client.newCall(okhttpRequest).execute()) {
                          ResponseBody responseBody = response.body();
                          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                          if (response.isSuccessful()) {
                            return new ProofStateClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, DeleteAnnotationQueueAssignmentResponse.class), response);
                          }
                          try {
                            switch (response.code()) {
                              case 400:throw new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                              case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                              case 403:throw new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                              case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                              case 405:throw new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                            }
                          }
                          catch (JsonProcessingException ignored) {
                            // unable to map error response, throwing generic error
                          }
                          Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                          throw new ProofStateClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
                        }
                        catch (IOException e) {
                          throw new ProofStateClientException("Network error executing HTTP request", e);
                        }
                      }
                    }
